 language: node_js
 node_js:
   - "0.10"
 before_script:
   - npm install -g grunt-cli bower
   - gem install compass --pre
   - bower install
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - ./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update
   - sleep 3

 notifications:
   email:
     - miaojian@wandoujia.com
