 language: node_js
 node_js:
   - "0.10"
 before_script:
   - npm install -g grunt-cli bower
   - npm install
   - gem install compass --pre
   - bower install
 notifications:
   email:
     - frontend@wandoujia.com
